spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deptspring?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #此处初次创建项目，hibernate会自动创建表格，后面用update即可
    show-sql: true
  redis:
    host: 192.168.203.128
    password:
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1ms